/*
===============================================================================
 Name        : webside.h
 Author      : Enrico Giordano - MakarenaLabs
 Version     : 1.0
 Copyright   : Copyright (C) 2013
 Description : HTML pages
===============================================================================
*/

unsigned char WebSide[100][100];

const unsigned char WebSide_guest[] = {
"<!doctype html>"
"<html>"
"<head>"
"<meta charset=\"utf-8\">"
"<style type=\"text/css\">"
""
"html {"
"    width: 100%;"
"    height: 100%;"
"}"
""
"body {"
"    width: 100%;"
"    height: 100%;"
"    background-color: #1ABC9C;"
"font: 14px \"Lato\", sans-serif;"
"}"
""
"#container{"
"width:100%;"
"}"
""
"#table{"
"margin-top:10%;"
"margin-left:25%;"
"margin-right:25%;"
"background-color:#ECF0F1;"
"border-radius:8px;"
"}"
""
"input{"
"margin:5%;"
"width: 35%;"
"font-size:30px;"
"color:#1ABC9C;"
"border-radius:8px;"
"border:groove;"
"}"
""
"#status{"
"background-color:#BDC3C7;"
"}"
""
"#chiudi{"
"width:20px;"
"height:20px;"
"background-color:#E74C3C;"
"border-color:#E74C3C;;"
"}"
""
"#chiudi:hover{"
"background-color:#C0392B;"
"border-color:# C0392B;"
"}"
""
"button{"
"margin:5%;"
"font-size:30px;"
"border-radius:10px;"
"color:#FFF;"
"font-size:center;"
"}"
""
"#button-invia{"
"border-color:#1ABC9C;"
"background:#1ABC9C;"
"width: 35%;"
"}"
""
"#button-invia:hover{"
"background-color:#2fe2bf;"
"border-color:#2fe2bf;"
"}"
""
".text{"
"text-align:center;"
"margin-top:25px;"
"color:#34495e;"
"font-weight:bold;"
"}"
""
"</style>"
"<title>Login</title>"
"</head>"
"<body>"
"<div id=\"container\">"
"<div id=\"table\">"
"    <div id=\"status\">"
" <button type=\"submit\" name=\"close\" id=\"chiudi\"></button>"
"</div>"
"<form action=\"\" method=\"get\">"
"        <input type=\"text\" name=\"pw\" placeholder=\"password\">"
"        <button type=\"submit\" id=\"button-invia\" name=\"\">Invia</button>"
"</form>   "
"</div>"
"    </div>"
"</body>"
"</html>"
};


const unsigned char WebSide_logged[] = {
"<!doctype html>"
"<html>"
"<head>"
"<meta charset=\"utf-8\">"
"<style type=\"text/css\">"
""
"html {"
"    width: 100%;"
"    height: 100%;"
"}"
""
"body {"
"    width: 100%;"
"    height: 100%;"
"    background-color: #1ABC9C;"
"font: 14px \"Lato\", sans-serif;"
"}"
""
"#container{"
"width:100%;"
"}"
""
"#table{"
"margin-top:10%;"
"margin-left:25%;"
"margin-right:25%;"
"background-color:#ECF0F1;"
"border-radius:8px;"
"}"
""
"#status{"
"background-color:#BDC3C7;"
"}"
""
"#chiudi{"
"width:20px;"
"height:20px;"
"background-color:#E74C3C;"
"border-color:#E74C3C;"
"}"
""
"#chiudi:hover{"
"background-color:#C0392B;"
"border-color:# C0392B;"
"}"
""
"button{"
"margin:5%;"
"font-size:30px;"
"border-radius:10px;"
"color:#FFF;"
"font-size:center;"
"font-weight:bold;"
"}"
""
".spazio{"
"width:50%;"
"height:50%;"
"text-align:center;"
"}"
""
".spazioled{"
"width:50%;"
"height:50%;"
"text-align:center;"
"float:left;"
"}"
""
"#led{"
"width:50%;"
"height:100px;"
"background-color:#f1c40f;"
"text-align:center;"
"font-size:20px;"
"border-color:#f1c40f;"
"}"
""
"#led:hover{"
"background-color:#f39c12;"
"border-color:#f39c12;"
"color:#34495e;"
"}"
""
"#suono{"
"width:50%;"
"height:100px;"
"background-color:#3498DB;"
"text-align:center;"
"font-size:20px;"
"border-color:#3498DB;"
"}"
""
"#suono:hover{"
"background-color:#2980B9;"
"border-color:#2980B9;"
"color:#34495e;"
"}"
""
"</style>"
"<title>Control Panel</title>"
"</head>"
"<body>"
"<div id=\"container\">"
"<div id=\"table\">"
"<div id=\"status\">"
"<form action=log method=\"get\">"
"    <button type=\"submit\" name=\"close\" id=\"chiudi\"></button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazioled\">"
"<form action=led method=\"get\" name=led>"
"    <button type=\"submit\" name=\"led\" value=1 id=\"led\">LED 1</button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazioled\">"
"<form action=led method=\"get\" name=led>"
"    <button type=\"submit\" name=\"led\" value=2 id=\"led\">LED 2</button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazioled\">"
"<form action=led method=\"get\" name=led>"
"    <button type=\"submit\" name=\"led\" value=3 id=\"led\">LED 3</button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazioled\">"
"<form action=led method=\"get\" name=led>"
"    <button type=\"submit\" name=\"led\" value=4 id=\"led\">LED 4</button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazioled\">"
"<form action=led method=\"get\" name=led>"
"    <button type=\"submit\" name=\"led\" value=5 id=\"led\">LED 5</button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazioled\">"
"<form action=led method=\"get\" name=led>"
"    <button type=\"submit\" name=\"led\" value=6 id=\"led\">LED 6</button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazioled\">"
"<form action=led method=\"get\" name=led>"
"    <button type=\"submit\" name=\"led\" value=7 id=\"led\">LED 7</button>"
"</form>"
"    </div>"
"    "
"    <div class=\"spazio\">"
"    <form action=sound method=\"get\" name=\"sound\">"
"    <button id=\"suono\" name=\"sound\" type=\"submit\">SOUND</button>"
"    </form>"
"    </div>    "
"    "
"</div>"
"</div>"
"</body>"
"</html>"
""
};
